openid_connect_gitlab.settings.gitlab:
  type: config_object
  label: 'OpenID Connect GitLab settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable client'
    settings:
      type: mapping
      mapping:
        client_id:
          type: string
          label: 'Client ID'
        client_secret:
          type: string
          label: 'Client secret'
        baseUrl:
          type: string
          label: 'Base URL'
